services:
  corevix-all-in-one:
    build: .
    container_name: corevix-all-in-one
    ports:
      - "5432:5432"
      - "27017:27017"
      - "6379:6379"
    volumes:
      - corevix_postgres_data:/var/lib/postgresql/data
      - corevix_mongodb_data:/data/db

volumes:
  corevix_postgres_data:
  corevix_mongodb_data:
